on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - id: extract-tag
        run: echo ::set-output name=DOCKER_TAG::$(echo ${GITHUB_REF#refs/tags/v})
      - uses: docker/build-push-action@v4
        with:
          push: true
          tags: mstmelody/radiko-podcast:latest,mstmelody/radiko-podcast:${{ steps.extract-tag.outputs.DOCKER_TAG }}
